import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/login">
            <button>login</button>
          </Link>
          <Link href="/register">
            <button>register</button>
          </Link>{" "}
          <Link href="/dashboard">
            <button>dashboard</button>
          </Link>{" "}
          <Link href="/dashboard/:id">
            <button>chat page</button>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
